baseURL = "https://bouncingbit.com/"
languageCode = "en-AU"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true
title = "bouncingbit test site"
theme = "ananke"
